<#
    Builds WindroseSync.exe using the C# compiler that ships with Windows.

    No .NET SDK required. Targets .NET Framework 4.8, preinstalled on Windows 10/11 -
    so players need no runtime download and the exe stays ~20 KB.

    The mod source is BAKED IN here, so players get a single file with nothing to
    configure. Rebuild if you ever move the repo.

    Examples:
      .\build.ps1 -Owner your-github-account
      .\build.ps1 -Owner your-github-account -GitRef v1.0.0
      .\build.ps1 -BaseUrl http://127.0.0.1:8899/        # local testing
#>
[CmdletBinding()]
param(
    [string]$Owner   = "",
    [string]$Repo    = "windrose-mod-sync",
    [string]$GitRef  = "main",
    [string]$BaseUrl = "",
    [switch]$Run
)

$ErrorActionPreference = "Stop"

$csc = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { throw "csc.exe not found. Is .NET Framework 4.x installed?" }

$here = $PSScriptRoot
$out  = Join-Path $here "publish"
New-Item -ItemType Directory -Force -Path $out | Out-Null

# Remember the last-used source so a bare rebuild doesn't silently produce an
# exe pointing nowhere.
$stateFile = Join-Path $here ".buildconfig.json"
if (-not $Owner -and -not $BaseUrl -and (Test-Path $stateFile)) {
    $prev = Get-Content $stateFile -Raw | ConvertFrom-Json
    $Owner   = $prev.Owner
    $Repo    = $prev.Repo
    $GitRef  = $prev.GitRef
    $BaseUrl = $prev.BaseUrl
    Write-Host "Reusing last source: $(if ($BaseUrl) { $BaseUrl } else { "$Owner/$Repo@$GitRef" })" -ForegroundColor DarkGray
}

if (-not $Owner -and -not $BaseUrl) {
    throw "Specify -Owner <github-account> (or -BaseUrl for self-hosting). This gets baked into the exe so players configure nothing."
}

@{ Owner = $Owner; Repo = $Repo; GitRef = $GitRef; BaseUrl = $BaseUrl } |
    ConvertTo-Json | Set-Content $stateFile -Encoding utf8

function Esc([string]$s) { if ($null -eq $s) { "" } else { $s.Replace('\', '\\').Replace('"', '\"') } }

$genPath = Join-Path $here "BuildConfig.cs"
@"
// GENERATED by build.ps1 - do not edit, do not commit.
// Baked in so the launcher is a single self-contained file for players.
namespace WindroseSync
{
    internal static class BuildConfig
    {
        public const string Owner   = "$(Esc $Owner)";
        public const string Repo    = "$(Esc $Repo)";
        public const string GitRef  = "$(Esc $GitRef)";
        public const string BaseUrl = "$(Esc $BaseUrl)";
    }
}
"@ | Set-Content -Path $genPath -Encoding utf8

$exe = Join-Path $out "WindroseSync.exe"
$refs = @("System.dll", "System.Core.dll", "System.Web.Extensions.dll")
$refArgs = $refs | ForEach-Object { "/reference:$_" }

Write-Host "Compiling..." -ForegroundColor Cyan
& $csc /nologo /target:exe /platform:anycpu /optimize+ /warn:4 `
       "/out:$exe" $refArgs (Join-Path $here "WindroseSync.cs") $genPath

if ($LASTEXITCODE -ne 0) { throw "Compilation failed (exit $LASTEXITCODE)" }

# A stale sidecar config would silently override the baked-in source.
$sidecar = Join-Path $out "WindroseSync.config.json"
if (Test-Path $sidecar) {
    Remove-Item $sidecar -Force
    Write-Host "Removed stale sidecar config (settings are baked in now)" -ForegroundColor DarkGray
}

$size = (Get-Item $exe).Length
Write-Host ("Built {0} ({1:N0} bytes)" -f $exe, $size) -ForegroundColor Green
Write-Host ("Source baked in: {0}" -f $(if ($BaseUrl) { $BaseUrl } else { "github.com/$Owner/$Repo @ $GitRef" }))
Write-Host ""
Write-Host "Players need this ONE file. Nothing to configure." -ForegroundColor Yellow

if ($Run) {
    Write-Host ""
    & $exe --verify --no-launch
}
